[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

# This redirect rule is critical for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 