// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytqjsleyncardpnjhmem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cWpzbGV5bmNhcmRwbmpobWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NjE2ODAsImV4cCI6MjA1ODQzNzY4MH0.E7AOADH-Kba5Y_iy8OK6lfO7SHkOC8lBOy_9QaqFFAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);